### PR TITLE
Allow checking if map_id is a tube or a wall

### PR DESCRIPTION
**Pull request by Brett208**
I have used this bit of code in 2 scenarios now so thought it should get pushed into OP2Helper

### CODE REVIEW

**Review by DanRStevens — APPROVED** [review]
Looks good.

I'm kind of curious about what uses it has. I know there is the `CreateTubeOrWallLine` method already. Is the usage related?

**Comment by Brett208** [comment]
Actually, I was wondering if we wanted to insert this functionality into the existing CreateTubeOrWallLine subroutine to block passing something like mapStructureFactory. I didn't take the time to test if the game already ignores calls to create a wall if a non-wall is passed.

I use it in the body of the subroutine below:

```C++
void RecordTubeOrWallLine(BuildingGroup &buildingGroup, int x1, int y1, int x2, int y2, map_id type)
```

Otherwise, you could add a line buildings or guard posts to your map instead of a line of tubes. And those options would be valid inputs into a buildingGroup (I think). EDIT: it is more complicated than this, but basic gist of what I'm preventing...

-Brett

**Comment by DanRStevens** [comment]
Ahh, will that also be added to OP2Helper? I haven't given much thought to what the game does when passed unexpected `map_id` values.

**Comment by Brett208** [comment]
I hadn't planned on adding RecordTubeOrWallLine. It mirrors the existing function but instead of making, it adds to a building queue.

I guess if it looks useful, I could push it as well. I don't like how many parameters it takes, but since I'm mimicking the existing function it sort of is what it is.

**Pull request merged**
